wandb_version: 1

dataset.batch_size:
  value: 16
dataset.val_split:
  value: 0.10457126500950878
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.Adam
net.optimizer.lr:
  value: 0.0007986348541058185
net.rnn_block.hidden_size:
  value: 256
net.rnn_block.num_layers:
  value: 3
net.width:
  value: 256
trainer.max_epochs:
  value: 59
