wandb_version: 1

dataset.batch_size:
  value: 32
dataset.val_split:
  value: 0.15044173087118096
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.SGD
net.optimizer.lr:
  value: 0.0008679321784409911
net.rnn_block.hidden_size:
  value: 128
net.rnn_block.num_layers:
  value: 3
net.width:
  value: 128
trainer.max_epochs:
  value: 129
