wandb_version: 1

dataset.batch_size:
  value: 64
dataset.val_split:
  value: 0.18497385674059347
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.SGD
net.optimizer.lr:
  value: 0.0008323644741809538
net.rnn_block.hidden_size:
  value: 64
net.rnn_block.num_layers:
  value: 3
net.width:
  value: 128
trainer.max_epochs:
  value: 148
