wandb_version: 1

dataset.batch_size:
  value: 128
dataset.val_split:
  value: 0.10010257155630978
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.Adam
net.optimizer.lr:
  value: 0.0006912507831707598
net.rnn_block.hidden_size:
  value: 128
net.rnn_block.num_layers:
  value: 1
net.width:
  value: 128
trainer.max_epochs:
  value: 104
