wandb_version: 1

dataset.batch_size:
  value: 128
dataset.val_split:
  value: 0.24300902338879007
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.Adam
net.optimizer.lr:
  value: 0.0009897158149582187
net.rnn_block.hidden_size:
  value: 64
net.rnn_block.num_layers:
  value: 1
net.width:
  value: 32
trainer.max_epochs:
  value: 187
