wandb_version: 1

dataset.batch_size:
  value: 192
dataset.val_split:
  value: 0.27131341209799564
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.SGD
net.optimizer.lr:
  value: 0.000614006124742842
net.rnn_block.hidden_size:
  value: 256
net.rnn_block.num_layers:
  value: 1
net.width:
  value: 128
trainer.max_epochs:
  value: 232
