wandb_version: 1

dataset.batch_size:
  value: 128
dataset.val_split:
  value: 0.24634965339091697
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.Adam
net.optimizer.lr:
  value: 0.000666370169494408
net.rnn_block.hidden_size:
  value: 64
net.rnn_block.num_layers:
  value: 3
net.width:
  value: 256
trainer.max_epochs:
  value: 152
