wandb_version: 1

dataset.batch_size:
  value: 192
dataset.val_split:
  value: 0.1741180338167582
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.SGD
net.optimizer.lr:
  value: 0.0009752130990605234
net.rnn_block.hidden_size:
  value: 128
net.rnn_block.num_layers:
  value: 3
net.width:
  value: 256
trainer.max_epochs:
  value: 115
