wandb_version: 1

dataset.batch_size:
  value: 32
dataset.val_split:
  value: 0.2396232192108945
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.SGD
net.optimizer.lr:
  value: 0.0007105962298427763
net.rnn_block.hidden_size:
  value: 64
net.rnn_block.num_layers:
  value: 1
net.width:
  value: 256
trainer.max_epochs:
  value: 258
