wandb_version: 1

dataset.batch_size:
  value: 64
dataset.val_split:
  value: 0.14861831789940205
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.Adam
net.optimizer.lr:
  value: 0.0004932486536034722
net.rnn_block.hidden_size:
  value: 512
net.rnn_block.num_layers:
  value: 2
net.width:
  value: 32
trainer.max_epochs:
  value: 249
