wandb_version: 1

dataset.batch_size:
  value: 192
dataset.val_split:
  value: 0.25413862732898407
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.SGD
net.optimizer.lr:
  value: 0.0006927264072228651
net.rnn_block.hidden_size:
  value: 64
net.rnn_block.num_layers:
  value: 2
net.width:
  value: 32
trainer.max_epochs:
  value: 189
