wandb_version: 1

dataset.batch_size:
  value: 128
dataset.val_split:
  value: 0.15195059730033028
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.SGD
net.optimizer.lr:
  value: 0.0005952989079136509
net.rnn_block.hidden_size:
  value: 512
net.rnn_block.num_layers:
  value: 3
net.width:
  value: 128
trainer.max_epochs:
  value: 206
