wandb_version: 1

dataset.batch_size:
  value: 192
dataset.val_split:
  value: 0.2755112851741641
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.SGD
net.optimizer.lr:
  value: 0.0007711768685238516
net.rnn_block.hidden_size:
  value: 512
net.rnn_block.num_layers:
  value: 1
net.width:
  value: 32
trainer.max_epochs:
  value: 125
