wandb_version: 1

dataset.batch_size:
  value: 64
dataset.val_split:
  value: 0.15589755673763564
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.SGD
net.optimizer.lr:
  value: 0.000779339613459288
net.rnn_block.hidden_size:
  value: 256
net.rnn_block.num_layers:
  value: 3
net.width:
  value: 256
trainer.max_epochs:
  value: 236
