wandb_version: 1

dataset.batch_size:
  value: 128
dataset.val_split:
  value: 0.15325756479835834
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.Adam
net.optimizer.lr:
  value: 0.0007675674376543849
net.rnn_block.hidden_size:
  value: 128
net.rnn_block.num_layers:
  value: 1
net.width:
  value: 64
trainer.max_epochs:
  value: 244
