wandb_version: 1

dataset.batch_size:
  value: 32
dataset.val_split:
  value: 0.11998684691210187
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.Adam
net.optimizer.lr:
  value: 0.0007910195233910223
net.rnn_block.hidden_size:
  value: 64
net.rnn_block.num_layers:
  value: 3
net.width:
  value: 32
trainer.max_epochs:
  value: 247
