wandb_version: 1

dataset.batch_size:
  value: 128
dataset.val_split:
  value: 0.1876505549416047
net.depth:
  value: 1
net.optimizer._target_:
  value: torch.optim.Adam
net.optimizer.lr:
  value: 0.00024174799805545523
net.rnn_block.hidden_size:
  value: 256
net.rnn_block.num_layers:
  value: 3
net.width:
  value: 32
trainer.max_epochs:
  value: 95
