_wandb:
    value:
        cli_version: 0.23.0
        e:
            w6cjs8qkpv4lm709vvh7xrrjb4yel3xm:
                codePath: src\experiment.py
                codePathLocal: src\experiment.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "509722226688"
                        used: "397309407232"
                email: mariapia.sorrentino2002@gmail.com
                executable: C:\Users\maria\Desktop\SAPIENZA\LEZIONI\FUNDATION OF DATA SCIENCE\Human Activity Recognition\FDS_PROJECT\.venv\Scripts\python.exe
                git:
                    commit: 415160a8a9e108ec321a882136a3fc28a083597a
                    remote: https://github.com/Catairu/FDS_PROJECT.git
                host: Mariapia
                memory:
                    total: "16952647680"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\maria\Desktop\SAPIENZA\LEZIONI\FUNDATION OF DATA SCIENCE\Human Activity Recognition\FDS_PROJECT\src\experiment.py
                python: CPython 3.12.0
                root: .
                startedAt: "2025-12-04T15:20:30.077910Z"
                writerId: w6cjs8qkpv4lm709vvh7xrrjb4yel3xm
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 41
                - 50
                - 106
            "2":
                - 1
                - 41
                - 50
                - 106
            "3":
                - 7
                - 13
                - 66
            "4": 3.12.0
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
cfg:
    value: '{''depth'': 1, ''width'': 256, ''num_classes'': 6, ''block'': {''_target_'': ''net.cnn.ConvBlock'', ''in_channels'': ''${net.width}'', ''out_channels'': ''${net.width}'', ''kernel_size'': 3, ''pool_size'': 2}, ''embed'': {''_target_'': ''net.cnn.ConvAutoencoder'', ''in_channels'': 9, ''encoded_channels'': ''${net.width}'', ''kernel_size'': 3, ''pool_size'': 2}, ''unembed'': {''_target_'': ''torch.nn.LazyLinear'', ''out_features'': 6}, ''optimizer'': {''_target_'': ''torch.optim.Adam'', ''lr'': 6e-05, ''weight_decay'': 0.001}, ''rnn_block'': {''_target_'': ''net.rnn.LSTMBlock'', ''input_size'': 128, ''hidden_size'': 128, ''num_layers'': 2, ''dropout'': 0.3, ''bidirectional'': False}}'
dataset:
    value:
        batch_size: 128
        data_dir: ./data
        val_split: 0.2
info:
    value:
        num_params: 440975
net:
    value:
        block:
            _target_: net.cnn.ConvBlock
            in_channels: 256
            kernel_size: 3
            out_channels: 256
            pool_size: 2
        depth: 1
        embed:
            _target_: net.cnn.ConvAutoencoder
            encoded_channels: 256
            in_channels: 9
            kernel_size: 3
            pool_size: 2
        num_classes: 6
        optimizer:
            _target_: torch.optim.Adam
            lr: 6e-05
            weight_decay: 0.001
        rnn_block:
            _target_: net.rnn.LSTMBlock
            bidirectional: false
            dropout: 0.3
            hidden_size: 128
            input_size: 128
            num_layers: 2
        unembed:
            _target_: torch.nn.LazyLinear
            out_features: 6
        width: 256
seed:
    value: 42
trainer:
    value:
        log_every_n_steps: 10
        max_epochs: 200
wandb:
    value:
        entity: catairu-sapienza-universit-di-roma
        name: max_epochs{max_epochs}_bs{batch_size}_valsplit{val_split}_depth{depth}_width{width}_opt{optimizer._target_}_lr{optimizer.lr}_hsize{rnn_block.hidden_size}_nlayers{rnn_block.num_layers}
        project: FDS_PROJECT
