_wandb:
    value:
        cli_version: 0.23.0
        e:
            k1uyotaq5nnefh0gwkzcv27j2zfmu480:
                codePath: src\experiment.py
                codePathLocal: experiment.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "509722226688"
                        used: "402798940160"
                email: mariapia.sorrentino2002@gmail.com
                executable: C:\Users\maria\Desktop\SAPIENZA\LEZIONI\FUNDATION OF DATA SCIENCE\Human Activity Recognition\FDS_PROJECT\.venv\Scripts\python.exe
                git:
                    commit: 9a9961171196f8a5bff0092e8f1f8a330aa37953
                    remote: https://github.com/Catairu/FDS_PROJECT.git
                host: Mariapia
                memory:
                    total: "16952647680"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\maria\Desktop\SAPIENZA\LEZIONI\FUNDATION OF DATA SCIENCE\Human Activity Recognition\FDS_PROJECT\src\experiment.py
                python: CPython 3.12.0
                root: .
                startedAt: "2025-12-01T16:31:49.514353Z"
                writerId: k1uyotaq5nnefh0gwkzcv27j2zfmu480
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 41
                - 50
                - 106
            "2":
                - 1
                - 41
                - 50
                - 106
            "3":
                - 7
                - 13
                - 66
            "4": 3.12.0
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
cfg:
    value: '{''depth'': 1, ''width'': 64, ''num_classes'': 6, ''block'': {''_target_'': ''net.cnn.ConvBlock'', ''in_channels'': 32, ''out_channels'': ''${.in_channels}'', ''kernel_size'': 3, ''pool_size'': 2}, ''embed'': {''_target_'': ''net.cnn.ConvAutoencoder'', ''in_channels'': 9, ''encoded_channels'': 32, ''kernel_size'': 3, ''pool_size'': 2}, ''unembed'': {''_target_'': ''torch.nn.LazyLinear'', ''out_features'': 6}, ''optimizer'': {''_target_'': ''torch.optim.Adam'', ''lr'': 0.001, ''weight_decay'': 0.0}, ''rnn_block'': {''_target_'': ''net.lstm.LSTMBlock'', ''input_size'': 32, ''hidden_size'': 128, ''num_layers'': 2, ''dropout'': 0.1, ''bidirectional'': False}}'
dataset:
    value:
        batch_size: 128
        data_dir: ../data
        num_workers: 4
        val_split: 0.2
info:
    value:
        num_params: 217295
net:
    value:
        block:
            _target_: net.cnn.ConvBlock
            in_channels: 32
            kernel_size: 3
            out_channels: 32
            pool_size: 2
        depth: 1
        embed:
            _target_: net.cnn.ConvAutoencoder
            encoded_channels: 32
            in_channels: 9
            kernel_size: 3
            pool_size: 2
        num_classes: 6
        optimizer:
            _target_: torch.optim.Adam
            lr: 0.001
            weight_decay: 0
        rnn_block:
            _target_: net.lstm.LSTMBlock
            bidirectional: false
            dropout: 0.1
            hidden_size: 128
            input_size: 32
            num_layers: 2
        unembed:
            _target_: torch.nn.LazyLinear
            out_features: 6
        width: 64
seed:
    value: 42
trainer:
    value:
        log_every_n_steps: 10
        max_epochs: 100
wandb:
    value:
        entity: catairu-sapienza-universit-di-roma
        name: experiment_1
        project: FDS_PROJECT
